name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:

  register-dataset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Dataset
        run: ls tourism_project/data

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install pandas

      - name: Data Preparation
        run: python tourism_project/data_prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r tourism_project/requirements.txt

      - name: Train Model
        run: python tourism_project/model_building/train.py

  deploy-hosting:
    needs: model-training
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deployment Successful"
