name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:

  register-dataset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Dataset
        run: ls -R

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Project Files
        run: |
          ls -R
          echo "Data verification successful"

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Model Files
        run: |
          ls -R
          echo "Model verification successful"

  deploy-hosting:
    needs: model-training
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deployment Successful"
